version: '3'
services:
  server:
    container_name: financeiro-server
    image: financeiro-server:desenv
    build:
      context: ./
      dockerfile: ./server/docker/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./server/src:/var/www
  client:
    container_name: financeiro-client
    image: financeiro-client:desenv
    build:
      context: ./
      dockerfile: ./client/docker/Dockerfile
    ports:
      - "81:80"
    volumes:
      - ./client/src:/var/www
