version: '3'
services:
  app:
    container_name: financeiro
    image: financeiro:desenv
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www
