version: '3'
services:
  server:
    container_name: financeiro-server
    image: financeiro-server:desenv
    build:
      context: ./
      dockerfile: ./server/docker/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./server/src:/var/www
  client:
    container_name: financeiro-client
    image: financeiro-client:desenv
    build:
      context: ./
      dockerfile: ./client/docker/Dockerfile
    ports:
      - "81:80"
    volumes:
      - ./client/src:/var/www
  bd:
    container_name: financeiro-bd
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - ./bd:/var/lib/mysql
      - ./server/etl/scripts/datamart:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: financeiro
      MYSQL_USER: usr_financeiro
      MYSQL_PASSWORD: pwd_financeiro

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

